name: ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.18
  - pip:
  # pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
    - --index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
    - torch==2.4.1
    - torchvision>=0.19.1
    - torchaudio==2.4.1
    - gym>=0.26.2
    - numpy>=1.21.0
    - pandas>=1.3.0
    - numexpr>=2.8.0
    - datasets>=4.0.0
    - matplotlib>=3.5.0
    - nltk>=3.8
    - torch-directml>=0.2.5  # Windows DirectML support version=0.2.5.dev240914